### ISSUE TITLE
I am keen to join your team and utilize my expertise to help achieve outstanding results on your projects.

### ISSUE THREAD

**Issue by kentaurse** [uvio-network/webclient#7]
Hi, I'm Ethan Tan, an expert in web full-stack and blockchain development with over 8 years of experience. I specialize in crafting durable, scalable web applications and innovative blockchain solutions. My proficiency in React.js, Vue.js, and Next.js, along with my expertise in Solidity for smart contracts, ensures I deliver superior, secure, and efficient solutions designed to meet your unique objectives.

**Comment by xh3b4sd** [comment]
Hello @kentaurse, thank you for reaching out. I did not have notifications on and didn't realize somebody created an issue.

If you want to contribute you can check the code for yourself and provide pull requests for changes that you think should be made. You could also write specs, work on the docs, or suggest a direction in which Uvio should develop. Let me know if you need anything!

**Comment by kentaurse** [comment]
I want to regular salary

**Comment by xh3b4sd** [comment]
We have no vacancies on a fixed salary basis at the moment. All contributions happen voluntarily right now.

**Comment by kentaurse** [comment]
I see
If you need regular employee, plz contact me
